site_name: Boost.Fit
docs_dir: doc/src
site_dir: doc/html/
repo_url: https://github.com/pfultz2/Fit
copyright: 'Copyright &#169; 2014 Paul Fultz II'
site_author: 'Paul Fultz II'
use_directory_urls: false
extra_javascript: [js/configure.js]
theme_dir: boost-theme
pages:
- Home: 'index.md'
- About:
    - 'Quick Start': 'quickstart.md'
    - 'Overview' : 'overview.md'
    - 'Basic Concepts' : 'concepts.md'
    - 'Requirements': 'requirements.md'
    - 'Acknowledgements': 'acknowledgements.md'
    - 'License': 'license.md'
- Adaptors:
    - 'by': 'by.md'
    - 'compose': 'compose.md'
    - 'conditional': 'conditional.md'
    - 'combine': 'combine.md'
    - 'compress': 'compress.md'
    - 'decorate': 'decorate.md'
    - 'fix': 'fix.md'
    - 'flip': 'flip.md'
    - 'flow': 'flow.md'
    - 'implicit': 'implicit.md'
    - 'indirect': 'indirect.md'
    - 'infix': 'infix.md'
    - 'lazy': 'lazy.md'
    - 'match': 'match.md'
    - 'mutable': 'mutable.md'
    - 'partial': 'partial.md'
    - 'pipable': 'pipable.md'
    - 'protect': 'protect.md'
    - 'result': 'result.md'
    - 'reveal': 'reveal.md'
    - 'reverse_compress': 'reverse_compress.md'
    - 'rotate': 'rotate.md'
    - 'static': 'static.md'
    - 'unpack': 'unpack.md'
- Decorators:
    - 'capture': 'capture.md'
    - 'if': 'if.md'
    - 'limit': 'limit.md'
    - 'repeat': 'repeat.md'
    - 'repeat_while': 'repeat_while.md'
- Functions:
    - 'always': 'always.md'
    - 'arg': 'arg.md'
    - 'construct': 'construct.md'
    - 'decay': 'decay.md'
    - 'identity': 'identity.md'
    - 'placeholders': 'placeholders.md'
- Utilities:
    - 'alias': 'alias.md'
    - 'apply': 'apply.md'
    - 'apply_eval': 'apply_eval.md'
    - 'eval': 'eval.md'
    - 'BOOST_FIT_STATIC_FUNCTION': 'function.md'
    - 'BOOST_FIT_STATIC_LAMBDA': 'lambda.md'
    - 'lift': 'lift.md'
    - 'is_callable': 'is_callable.md'
    - 'pack': 'pack.md'
    - 'returns': 'returns.md'
    - 'tap': 'tap.md'
